name: PR Checks for Any Batch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  file_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate directory structure for modified batches
        run: |
          modified_batches=$(git diff --name-only origin/main | grep -oE '^Batch[0-9]+' | uniq)
          if [ -z "$modified_batches" ]; then
            echo "No batch directories modified."
            exit 0
          fi
          done

      - name: Check file naming conventions
        run: |
          for file in $(git diff --name-only origin/main); do
            if [[ ! "$file" =~ ^Batch[0-9]+/(LessonMaterials|Assignments|Comments)/[a-zA-Z0-9_.-]+$ ]]; then
              echo "Error: Invalid file name or path $file" >&2
              exit 1
            fi
          done
